// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_AULA.MODEL.Models;

public partial class Unidade
{
    public int UnCodigo { get; set; }

    public string UnDescricao { get; set; }

    public bool UnDesativado { get; set; }

    public virtual ICollection<Produto> Produtos { get; set; } = new List<Produto>();
}