// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_AULA.MODEL.Models;

public partial class Vendum
{
    public int VenCodigo { get; set; }

    public DateTime VenData { get; set; }

    public int VenCodigoCliente { get; set; }

    public string VenUsuario { get; set; }

    public int VenCodigoTipoPagamento { get; set; }

    public int? VenQtdParcelas { get; set; }

    public virtual ICollection<ItensVendum> ItensVenda { get; set; } = new List<ItensVendum>();

    public virtual ICollection<Parcela> Parcelas { get; set; } = new List<Parcela>();

    public virtual Cliente VenCodigoClienteNavigation { get; set; }

    public virtual TipoPagamento VenCodigoTipoPagamentoNavigation { get; set; }
}